# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release next/*

on:
  push:
    branches: [next/*]
    paths:
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g yarn lerna
      - run: yarn

      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(branch=${GITHUB_REF#refs/heads/}; echo ${branch/\//.})"
        id: extract_tag
      - run: node scripts/setVersion.js --tag ${{ steps.extract_tag.outputs.tag }}

      - run: yarn build

      - run: lerna exec --scope @microsoft/* -- "npm publish --tag ${{ steps.extract_tag.outputs.tag }} --access=public"
        if: github.repository == 'microsoftgraph/microsoft-graph-toolkit'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
