# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy pr storybook

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
    branches: [main, release/**, next/**]

permissions:
  pull-requests: write
  contents: write

jobs:
  storybook:
    if: "contains(github.event.pull_request.labels.*.name, 'Build: Storybook')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps ðŸ› 
        run: |
          echo "installing yarn"
          npm install -g yarn
          echo "installing deps for packages"
          yarn
      - name: Extract tag name
        shell: bash
        run: |
          tag=$(branch=${{ github.event.pull_request.head.ref }}; echo ${branch/\//.})
          if [[ $tag == next.* ]];
          then
            echo "##[set-output name=tag;]$tag"
          else
            echo "##[set-output name=tag;]pr.${{ github.event.pull_request.number }}"
          fi
        id: extract_tag
      - run: node scripts/setVersion.js --tag ${{ steps.extract_tag.outputs.tag }}

      - name: Build ðŸ› 
        run: |
          yarn build
          yarn storybook:build

      - name: Deploy mgt.dev/next/pr/${{ github.event.number }} ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: storybook-static
          target-folder: next/pr/${{ github.event.number }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: 'ðŸ“– The updated storybook is available [here](https://mgt.dev/next/pr/${{ github.event.number }})'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: 'ðŸ“– The updated storybook is available'
          mode: recreate
